apiVersion: v1
name: harbor-scanner-khulnasoft
version: 0.31.2
appVersion: 0.31.2
description: Harbor scanner adapter for Trivy
keywords:
  - scanner
  - harbor
  - vulnerability
sources:
- https://github.com/khulnasoft/harbor-scanner-khulnasoft
