apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-khulnasoft.fullname" . }}
  labels:
{{ include "harbor-scanner-khulnasoft.labels" . | indent 4 }}
type: Opaque
data:
  khulnasoft_username: {{ required "Khulnasoft username is required!" .Values.scanner.khulnasoft.username | b64enc | quote }}
  khulnasoft_password: {{ required "Khulnasoft password is required!" .Values.scanner.khulnasoft.password | b64enc | quote }}
