apiVersion: v1
kind: Secret
metadata:
  name: {{ include "harbor-scanner-khulnasoft.fullname" . }}-registry
  labels:
{{ include "harbor-scanner-khulnasoft.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}