apiVersion: v1
kind: Service
metadata:
  name: {{ include "harbor-scanner-khulnasoft.fullname" . }}
  labels:
{{ include "harbor-scanner-khulnasoft.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "harbor-scanner-khulnasoft.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: api-server
      protocol: TCP
      port: {{ .Values.service.port | default 8080 }}
      targetPort: {{ .Values.service.port | default 8080 }}
