apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor-scanner-khulnasoft.fullname" . }}
  labels:
{{ include "harbor-scanner-khulnasoft.labels" . | indent 4 }}
imagePullSecrets:
  - name: {{ include "harbor-scanner-khulnasoft.fullname" . }}-registry
